apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alloy-dev
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: alloy.dev.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: alloy-service
            port:
              number: 12345
