apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: app-dev
  labels:
    app: app
    environment: dev
spec:
  type: ClusterIP
  selector:
    app: app
    environment: dev
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  sessionAffinity: None
